#! /bin/sh


case "$1" in
  start)
	echo -n "Starting httpd: "
	start-stop-daemon -S -b -x httpd -- -h /srv/www
	echo "done"
	;;

  stop)
	echo -n "Stopping httpd: "
	start-stop-daemon -K httpd
	;;

  restart)
	$0 stop
	$0 start
	;;

  *)
	echo "Usage: syslog { start | stop | restart }" >&2
	exit 1
	;;
esac
