#! /bin/sh


case "$1" in
  start)
	echo -n "Starting networking: "
	/sbin/ifconfig lo 127.0.0.1 up
	start-stop-daemon -S -b -x udhcpc -- -i eth0
	echo "done"
	;;

  stop)
	echo -n "Stopping networking: "
	start-stop-daemon -K udhcp
	;;

  restart)
	$0 stop
	$0 start
	;;

  *)
	echo "Usage: syslog { start | stop | restart }" >&2
	exit 1
	;;
esac
