#! /bin/sh


case "$1" in
  start)
	echo -n "Starting TCP stream server: "
	start-stop-daemon -S -b -x tcpsvd -- -c 1 0 8000 /usr/bin/rescue-tcp-stream
	echo "done"
	;;

  stop)
	echo -n "Stopping TCP stream server: "
	start-stop-daemon -K tcpsvd
	;;

  restart)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: syslog { start | stop | restart }" >&2
	exit 1
	;;
esac
