include ${BUILDVAR_BUILDVARS_SCRIPT_DIR}/_generic_.mk

ACLOCAL_VERSION = 1.16

_BUILDVAR_ACLOCAL = \
	aclocal \
	--system-acdir='${BUILDVAR_ACLOCALDIR}/' \
	--automake-acdir='${BUILDVAR_STAGING_DATADIR_NATIVE}/aclocal-${ACLOCAL_VERSION}' \
	${BUILDVAR_ACLOCALEXTRAPATH} \

_BUILDVAR_CONFIGURE_FLAGS = \
	${BUILDVAR_CONFIGUREOPTS} \
	${BUILDVAR_EXTRA_OECONF} \
	CC='${BUILDVAR_CC}' \
	CFLAGS='${BUILDVAR_CFLAGS}' \
	CPPFLAGS='${BUILDVAR_CPPFLAGS}' \
	LDFLAGS='${BUILDVAR_LDFLAGS}' \

CONFIGURE_EXTRA_FLAGS ?=

AUTORECONF ?= autoreconf -i -f
CONFIGURE ?=  ./configure

export ACLOCAL = ${_BUILDVAR_ACLOCAL}

autoreconf:
	${AUTORECONF}

configure:
	${CONFIGURE} ${_BUILDVAR_CONFIGURE_FLAGS} ${CONFIGURE_EXTRA_FLAGS}
