include ${BUILDVAR_BUILDVARS_SCRIPT_DIR}/_generic_.mk

_BUILDVAR_ACLOCAL = \
	aclocal \
	--system-acdir='${BUILDVAR_ACLOCALDIR}/' \
	${BUILDVAR_ACLOCALEXTRAPATH} \

_BUILDVAR_CONFIGURE_FLAGS = \
	${BUILDVAR_CONFIGUREOPTS} \
	${BUILDVAR_EXTRA_OECONF} \
	CC='${BUILDVAR_CC}' \
	CFLAGS='${BUILDVAR_CFLAGS}' \
	LDFLAGS='${BUILDVAR_LDFLAGS}' \

CONFIGURE_EXTRA_FLAGS ?=

AUTORECONF ?= autoreconf -i -f
CONFIGURE ?=  ./configure

autoreconf: export ACLOCAL=${_BUILDVAR_ACLOCAL}
autoreconf:
	${AUTORECONF}

configure:
	${CONFIGURE} ${_BUILDVAR_CONFIGURE_FLAGS} ${CONFIGURE_EXTRA_FLAGS}
