include ${BUILDVAR_BUILDVARS_SCRIPT_DIR}/_generic_.mk

BUILD_FLAGS = \
	CROSS_COMPILE='${BUILDVAR_TARGET_PREFIX}' \
	CC='${BUILDVAR_KERNEL_CC} ${BUILDVAR_TOOLCHAIN_OPTIONS}' \
	LD='${BUILDVAR_KERNEL_LD} ${BUILDVAR_TOOLCHAIN_OPTIONS}' \

%:
	${MAKE} ${BUILD_FLAGS} $@

check-syntax:
	${MAKE} ${BUILD_FLAGS} -f flymake.mk
