#! /bin/bash

: ${STAGINGDIR:="@STAGINGDIR@"}
: ${MACHINCDIR:="@MACHINCDIR@"}
: ${MACHDATADIR:="@MACHDATADIR@"}
: ${PROJECT_TOPDIR:="@PROJECT_TOPDIR@"}
: ${KERNEL_DIR:="@KERNEL_DIR@"}
: ${KERNEL_DTREE_DIR:="@KERNEL_DTREE_DIR@"}
: ${PKGDATA_DIR="@PKGDATA_DIR@"}
: ${MAKE:=make}
: ${DTC_CPPFLAGS:=}
: ${srcdir:=.}

eval set -- `getopt -o 't:o:Pp:s' --long tftp:outdir:pins:nopins:pinflags:silent,overlay -- "$@"`

arg_out=.dtb
arg_makeflags=( --no-print-directory )
is_overlay=false

while true; do
    a=$1
    shift
    case $a in
      -t|--tftp)	echo "DEPRECATED: '--tftp' is not supported anymore" >&2; shift;;
      -o|--outdir)	arg_out=$1; shift;;
      -p|--pins)	echo "DEPRECATED: '--pins' is not supported anymore" >&2; shift;;
      -P|--nopins)	echo "WARNING: -P|--nopins are not supported anymore and will be removed in later versions" >&2;;
      -s|--silent)	arg_makeflags+=( -s );;
      --pinflags)	echo "DEPRECATED: '--pinflags' is not supported anymore" >&2; shift;;
      --overlay)	is_overlay=true;;
      --)		break;;
      *)		echo "internal error" >&2; exit 1;;
    esac
done

## _extend_dtc_cppflags <include-paths>
_extend_dtc_cppflags() {
    local IFS=:
    local i

    eval set -- $*
    for i; do
	DTC_CPPFLAGS+=" -I $i"
    done
}

mx6_split_variants() {
    local dstvar=$1
    local old_IFS=$IFS

    IFS=:
    eval set -- $2
    IFS=$old_IFS

    eval ${dstvar}_module+=$1
    eval ${dstvar}_soc+=$2
    eval ${dstvar}_memory+=$3
}

doit_generic() {
  local dts=$1
  local _make=(
    ${MAKE} -C "$arg_out"
    "${arg_makeflags[@]}"
  )
  local dtbflags=(
    VPATH="`pwd`:${srcdir}:$MACHINCDIR"
    VARIANTS="${dts%%.dts}"
    MACHINE_INCDIR="${MACHINCDIR##$STAGINGDIR}"
    KERNEL_DIR="${KERNEL_DIR}"
    KERNEL_DTREE_DIR="${KERNEL_DTREE_DIR}"
    DTB_SUFFIX=".$DTB_SUFFIX"
  )

  "${_make[@]}" -f "${PKGDATA_DIR}/devicetree.mk" "${dtbflags[@]}"
}

set -e
mkdir -p "$arg_out"

if $is_overlay; then
    DTB_SUFFIX=dtbo
else
    DTB_SUFFIX=dtb
fi

export DTC_CPPFLAGS
_extend_dtc_cppflags "`pwd`" "${DTC_INC_PATH}"

doit_generic "$@"

base=${1%%.dts}
fname=${base##*/}

rm -f "$arg_out/$fname-rev.dts"
dtc -I dtb -O dts -q --sort -o "$arg_out/$fname-rev.dts" "$arg_out/$base.${DTB_SUFFIX}"
chmod a-w "$arg_out/$fname-rev.dts"
